# Generated by Django 3.1.5 on 2021-02-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField()),
                ('location', models.CharField(choices=[('Boston', 'Boston'), ('Cambridge', 'Cambridge'), ('Watertown', 'Watertown'), ('Stoneham', 'Stoneham'), ('Randolph', 'Randolph')], max_length=15)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(upload_to='')),
                ('creator', models.CharField(max_length=30)),
            ],
        ),
    ]
