# Generated by Django 3.1.5 on 2021-02-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb',
            name='picture',
            field=models.ImageField(default='image.jpg', upload_to='media'),
        ),
    ]
