# Generated by Django 3.1.5 on 2021-02-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnar_app', '0002_auto_20210208_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('location', models.CharField(choices=[('Boston', 'Boston'), ('Cambridge', 'Cambridge'), ('Watertown', 'Watertown'), ('Stoneham', 'Stoneham'), ('Randolph', 'Randolph')], max_length=15)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('kind', models.PositiveIntegerField(choices=[(1, 'Strange beta'), (2, 'Breakfast at open'), (3, 'Snack given to teammate')])),
            ],
        ),
        migrations.CreateModel(
            name='MeetingAttended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('date', models.PositiveIntegerField(choices=[(1, 'February 2nd'), (2, 'February 16th'), (3, 'March 2nd')])),
            ],
        ),
        migrations.CreateModel(
            name='MeetingGameWon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('date', models.PositiveIntegerField(choices=[(1, 'February 2nd'), (2, 'February 16th'), (3, 'March 2nd')])),
            ],
        ),
        migrations.CreateModel(
            name='MiscellaneousPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('points', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutAttended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('date', models.PositiveIntegerField(choices=[(1, 'January 28th'), (2, 'February 4th'), (3, 'February 11th'), (4, 'February 18th'), (5, 'February 25th')])),
            ],
        ),
    ]
