# Generated by Django 3.1.5 on 2021-02-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnar_app', '0004_climbcomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='climb',
            name='reset',
            field=models.BooleanField(default=False),
        ),
    ]
