# Generated by Django 3.1.5 on 2021-02-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnar_app', '0005_climb_reset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=300)),
                ('climb_id', models.PositiveIntegerField()),
                ('time_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResetReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('climb_id', models.PositiveIntegerField()),
                ('time_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
